---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mouseion
  description: Internal document sharing system for FLYWHEEL
  annotations:
    github.com/project-slug: caddijp/mouseion
    backstage.io/source-location: url:https://github.com/caddijp/mouseion
  tags:
    - touches-customer-data
spec:
  type: repository
  lifecycle: production
  owner: group:TODO-set-owner
