name: Deploy mouseion to GAE and upload documents to GCS
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: GCP Authenticate
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      - name: Deploy mouseion to GAE
        uses: actions/gcloud/cli@master
        with:
          args: app deploy --project flywheel-mouseion
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: GCP Authenticate
        uses: actions/gcloud/auth@master
        env:
          GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      - name: Upload documents to flywheel-mouseion bucket
        uses: docker://gcr.io/cloud-builders/gsutil
        with:
          args: -m rsync -d -r docs gs://flywheel-mouseion/mouseion
