name: Upload
on:
  push:
    branches: [master]
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: flywheel-jp/mouseion/upload@master
        with:
          service-account-key: ${{ secrets.GCLOUD_AUTH }}
          namespace: mouseion
